# Generated by Django 4.1.7 on 2023-10-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=50),
        ),
    ]
